import {
  OPEN_CURLY_BRACKET,
  CLOSE_CURLY_BRACKET,
  COLON,
  SPACE,
  OPEN_BRACKET,
  CLOSE_BRACKET,
  CLOSE_BRACKET_WITH_SPACES_REGEX,
  CLOSE_CURLY_BRACKET_WITH_SPACES_REGEX,
  COLON_WITH_SPACES_REGEX,
  NEW_LINE_REGEX,
  OPEN_BRACKET_WITH_SPACES_REGEX,
  OPEN_CURLY_BRACKET_WITH_SPACES_REGEX,
  SPACES_REGEX,
} from '../constants';

export const minifyGQLQuery = (query: string) => {
  return query
    .replace(NEW_LINE_REGEX, SPACE)
    .replace(OPEN_CURLY_BRACKET_WITH_SPACES_REGEX, OPEN_CURLY_BRACKET)
    .replace(CLOSE_CURLY_BRACKET_WITH_SPACES_REGEX, CLOSE_CURLY_BRACKET)
    .replace(OPEN_BRACKET_WITH_SPACES_REGEX, OPEN_BRACKET)
    .replace(CLOSE_BRACKET_WITH_SPACES_REGEX, CLOSE_BRACKET)
    .replace(COLON_WITH_SPACES_REGEX, COLON)
    .replace(SPACES_REGEX, SPACE)
    .trim();
};
