import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import config from '../../tailwind.config';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  const theme = config.daisyui.themes[0];

  return (
    <html lang='en' data-theme={theme}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
